version: '3.8'

services:
  # 1. 백엔드 서비스 (FastAPI)
  backend:
    build: ./backend
    container_name: diet_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app  # 코드 수정 시 실시간 반영 (Hot Reload)
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=diet_db
    depends_on:
      - db

  # 2. 데이터베이스 서비스 (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: diet_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=diet_db
    volumes:
      - ./data/db:/var/lib/postgresql/data  # 데이터 영구 저장